  - name: Copy file with owner and permissions
    copy:
      src: lamp.php
      owner: root
      group: root
      dest: /usr/share/httpd/noindex/lamp.php
      #dest: /var/www/html/lamp.php
      mode: '0644'
    notify:
    - restart httpd
    - restart apache
    when: ansible_os_family == "RedHat"