  - name: Copy file with owner and permissions
    copy:
      src: lamp.php
      owner: satya
      group: satya
      dest: /var/www/html/lamp.php
      mode: '0644'
    notify:
    - restart httpd
    - restart apache
    when: ansible_os_family == "RedHat"