---
- hosts: all
  become: yes
  tasks:
  - name: installing apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart apache
    when: ansible_os_family == "Debian"
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify:
    - restart httpd    
    when: ansible_os_family == "RedHat"    
  
  - name: installing php
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - php
    - libapache2-mod-php
    - php-mcrypt 
    - php-mysql  
    notify:
    - restart apache 
    when: ansible_os_family == "Debian"
  - name: install php
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - php
    - php-mysql
    notify: 
    when: ansible_os_family == "RedHat"     
  
  - name: Copy file with owner and permissions
    copy:
      src: /home/satya/lamp.php
      owner: satya
      group: satya
      dest: /var/www/html/lamp.php
      mode: '0644'
    notify:
    when: ansible_os_family == "RedHat"

  handlers:
  - name: restart apache 
    service:
      name: apache2
      state: restarted  
    when: ansible_os_family == "Debian"
  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"                 
